### ISSUE TITLE
external permalink が設定されたパーマリンクをダイレクトにアクセスするとリダイレクトされない

### ISSUE THREAD

**Issue by waviaei** [tarosky/taro-external-permalink#5]
## 再現

1. しんきに記事を作成し、タイトルに適当に文字列を入れる。例 `hoge`
2. externla permalink でリダイレクト先を設定して公開する。
3. 公開したらその記事のパーマリンクが表示されるのでそれをコピーする。例 `https://example.com/news/hoge/`
4. 新しいタブで2のURLをペーストして直接アクセスしてみる 👉 その投稿がリダイレクトされずに普通に表示される
5. 4の記事が表示されるアーカイブ表示へアクセスする。例；`https://example.com/news/`
6. 記事詳細へのリンクをクリックする　👉　設定して external へリダイレクトされる

## 確認

ステップ4の挙動は仕様なのか、バグなのか？
仕様の場合、リダイレクトされるのが正しいように思う。必要であれば変更/選択できるようにする必要があるかもしれない

**Comment by fumikito** [comment]
- external link が設定されている場合、そのページは caoninical リンクをheadに出します
- リダイレクトしないのは、その個別ページにアクセスするのは検索エンジンなどが多いはずなので、わざわざリダイレクトするまでもないかと判断してのことです。

なので、仕様としています。課題としてリダイレクトを立てておきます
#8
